# Generated by Django 3.2.3 on 2021-07-20 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('start_time', models.TimeField(default=0)),
                ('stop_time', models.TimeField(default=0)),
                ('totla_time', models.TimeField(default=0)),
            ],
        ),
    ]
