# Generated by Django 3.2.3 on 2021-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0002_auto_20210721_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedetail',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timedetail',
            name='stop_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timedetail',
            name='totla_time',
            field=models.TimeField(blank=True),
        ),
    ]
