# Generated by Django 3.2.3 on 2021-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0004_auto_20210721_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedetail',
            name='start_time',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='timedetail',
            name='stop_time',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='timedetail',
            name='totla_time',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
    ]
