# Generated by Django 3.2.3 on 2021-07-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0005_auto_20210721_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timedetail',
            old_name='totla_time',
            new_name='total_time',
        ),
    ]
