# Generated by Django 3.2.3 on 2021-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0006_rename_totla_time_timedetail_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedetail',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
