# Generated by Django 3.2.3 on 2021-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0007_timedetail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedetail',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
