# Generated by Django 3.2.3 on 2021-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0008_timedetail_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedetail',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
