# Generated by Django 3.2.3 on 2021-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
