# Generated by Django 3.2.3 on 2021-05-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobs_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('now1', models.TimeField(default=0)),
                ('now2', models.TimeField(default=0)),
                ('job', models.ManyToManyField(blank=True, to='jobs.Jobs', verbose_name='محصولات')),
            ],
        ),
    ]
