# Generated by Django 3.2.3 on 2021-05-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210520_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobstime',
            options={'verbose_name': 'work', 'verbose_name_plural': 'works'},
        ),
    ]
