# Generated by Django 3.2.3 on 2021-05-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210520_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstime',
            name='job',
        ),
        migrations.AddField(
            model_name='jobstime',
            name='maintitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
    ]
