# Generated by Django 3.2.3 on 2021-06-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210524_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstime',
            name='maintitle',
        ),
    ]
