# Generated by Django 3.2.3 on 2021-06-10 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_jobstime_maintitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstime',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
